include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - avoid_print
    - always_declare_return_types
    - avoid_dynamic_calls
    - prefer_single_quotes
    - sort_constructors_first
    - unawaited_futures
    - cancel_subscriptions
    - close_sinks
    - only_throw_errors
    - prefer_relative_imports

analyzer:
  exclude:
    - "**/*.g.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
